package com.example.ericb.bluetoothobd;

import android.bluetooth.BluetoothAdapter;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.method.ScrollingMovementMethod;
import android.util.Log;
import android.widget.TextView;


/*
* A bluetooth adapter is the actual adapter on the hardware device.
* A bluetooth device is a device the adapter is either paired with or is able to discover locally.
* A bluetooth socket is what the devices communicate through.
 */

public class MainActivity extends AppCompatActivity {

    private BTOBDCommunication obd;



    /*
    * This is the default onCreate method generated by AndroidSDK
    */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }



    /*
    * onStart() happens after the app has been created
    *
    * The URL below has a nice image of activities in android and when they happen or interact with each other
    * https://developer.android.com/guide/components/activities/activity-lifecycle.html
    *
    * Multiple threads are used since some tasks block and we do not want to block the UI thread
    */
    @Override
    protected void onStart() {
        super.onStart();

        //The TextView info is used to show the current state of the application as well as the results.
        //Finding the TextView by the ID set in activity_main.xml and setting it to be scrollable
        TextView info = (TextView) findViewById(R.id.info);

        //Getting the default BluetoothAdapter of the device since some devices may have more than one
        //the bluetooth adapter will be null if there isn't an adapter or the adapter was not turned on
        BluetoothAdapter ba = BluetoothAdapter.getDefaultAdapter();

        //Create a connection with a bluetooth device if it actually has bluetooth capabilities
        if (isBluetoothEnabled(ba)) {
            obd = new BTOBDCommunication(ba, info);

            obd.start(); //Start thread
        }
    }



    /*
     * Release any resources used on app deconstruction, in this case the thread(s)
     */
    @Override
    protected void onDestroy() {
        super.onDestroy();

        //TextView for displaying information
        TextView info = (TextView) findViewById(R.id.info);

        info.append("Closing threads...\n");
        try{
            obd.join();
        }catch(Exception e){
            Log.e("Exception", e.toString());
        }

    }




    /*
    * Goes through bluetooth initiation, checking if bluetooth is supported and turned on
    * This will turn on the bluetooth adapter if it is off
    */
    private boolean isBluetoothEnabled(BluetoothAdapter b)
    {
        //TextView for displaying information
        TextView info = (TextView) findViewById(R.id.info);

        info.setText("Checking if Bluetooth is supported and enabled...\n");

        if (b == null)
        {
            info.append("This device does not support Bluetooth\n");
            return false;
        }
        else// Device DOES support Bluetooth
        {
            b.getDefaultAdapter().enable();
            try{
                wait(5000); //Wait a moment for the adapter to come online
            }
            catch (Exception e){
                Log.e("Exception", e.toString());
            }

            return true;
        }
    }



}
